### ISSUE TITLE
Some Jenkins Events Are Missing In Splunk

### ISSUE THREAD

**Issue by mikenau** [splunk/splunkforjenkins#4]
### Environment
Jenkins Enterprise: `1.642.18.1`
Jenkins Splunk Plugin: `1.6.4`
Splunk App For Jenkins: `1.0.7`

### Configuration
![image](https://user-images.githubusercontent.com/4041559/38645274-5c3a101c-3d98-11e8-8ebc-07c1edb30ffc.png)

### Issue
We are seeing some of our build data from Jenkins missing in Splunk. I'm trying to figure out where things are breaking down. Here's what we are seeing:

`index=jenkins_statistics source="/job_event" job_name="IBPMonitoring/IBP-Monitoring-Job*" host=xxxxxxxxxx type=completed | stats count by build_number | sort - build_number`

![image](https://user-images.githubusercontent.com/4041559/38645347-99ea700a-3d98-11e8-88f6-0801906db750.png)

Notice how there is no completed log for jobs 76, 73, and 71. These jobs did run though on Jenkins:

![image](https://user-images.githubusercontent.com/4041559/38645129-d000dd10-3d97-11e8-8f18-3de17ee1c526.png)

I cannot find anything on the Jenkins side indicating there was an error encountered during the execution of these jobs while communicating with Splunk. We see similar behavior on many of our jobs. 

Any idea what might be causing these events to not show up in splunk? Anywhere we can check for potential errors?

**Comment by fengxx** [comment]
one possible cause is indexer/heavy forwarder is too busy to handle data input,  please check your jenkins.log for message like 
>Server is busy, maybe caused by blocked queue, please check https://wiki.splunk.com/Community:TroubleshootingBlockedQueues

If you find similar error in jenkins log, you probably need to find the root cause via splunk search 
`index=_internal source=*metrics* blocked=true`

If your splunk indexer/heavy forwarder is using DEFAULT config, you may need adjust the queue size to larger value, e.g.
SPLUNK_HOME/etc/system/local/server.conf 
```
[queue]
maxSize = 5MB
```

**Comment by mikenau** [comment]
Thanks @fengxx. We suspect it's an issue on the HEC side of things at this point.
